/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    // Apply the maven publish to publish your package to maven repositories
    `maven-publish`
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "io.smithy.example"
            artifactId = "decorators"
            version = "1.0"

            from(components["java"])
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.0")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    val smithyVersion: String by project
    implementation("software.amazon.smithy:smithy-model:$smithyVersion")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
