name: git-secrets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  git-secrets:
    runs-on: macos-latest
    name: Git Secrets

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
      - name: Installing scanning tool
        run: |
          brew install git-secrets
          git secrets --install
          git secrets --register-aws
      - name: Running scanning tool
        run:
          git secrets --scan
